apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-dev.fullname" . }}
  labels:
    {{- include "hello-dev.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "hello-dev.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-dev.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-dev.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/bin/sh", "-c"]
          args:
            - >
              echo "Starting app...";
              java -jar /app/app.jar;
              echo "App finished - keeping container alive for demo";
              tail -f /dev/null

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}